import { Listing } from "@/lib/marketplace-types";

export const listings: Listing[] = [
  {
    id: "1",
    title: "Precision Components Manufacturing Unit",
    isVerified: true,
    propertyType: "Factory",
    price: 220000000,
    operationalStatus: "Running",
    state: "Maharashtra",
    city: "Pune",
    powerLoadKva: 2100,
    landAreaAcres: 4.2,
  },
  {
    id: "2",
    title: "Heavy Engineering Industrial Campus",
    isVerified: false,
    propertyType: "Factory",
    price: 185000000,
    operationalStatus: "Closed",
    state: "Gujarat",
    city: "Ahmedabad",
    powerLoadKva: 1700,
    landAreaAcres: 3.7,
  },
  {
    id: "3",
    title: "Industrial Skills Development College",
    isVerified: true,
    propertyType: "College",
    price: 98000000,
    operationalStatus: "Running",
    state: "Tamil Nadu",
    city: "Chennai",
    powerLoadKva: 900,
    landAreaAcres: 2.1,
  },
  {
    id: "4",
    title: "Automated Logistics Warehouse Block",
    isVerified: true,
    propertyType: "Warehouse",
    price: 124000000,
    operationalStatus: "Running",
    state: "Karnataka",
    city: "Bengaluru",
    powerLoadKva: 1200,
    landAreaAcres: 2.8,
  },
  {
    id: "5",
    title: "Distribution Warehouse and Sorting Hub",
    isVerified: false,
    propertyType: "Warehouse",
    price: 76000000,
    operationalStatus: "Closed",
    state: "Haryana",
    city: "Gurugram",
    powerLoadKva: 650,
    landAreaAcres: 1.9,
  },
  {
    id: "6",
    title: "Technical College in Industrial Cluster",
    isVerified: true,
    propertyType: "College",
    price: 112000000,
    operationalStatus: "Closed",
    state: "Maharashtra",
    city: "Nagpur",
    powerLoadKva: 840,
    landAreaAcres: 2.3,
  },
];
